fix logcat

diff --git a/system/bin/bcc_magisk b/system/bin/bcc_magisk
--- a/system/bin/bcc_magisk
+++ b/system/bin/bcc_magisk
@@ -75,7 +75,7 @@ W='\e[01;37m'
 convert(){
 	#Convert to decimal value
 	if [ $1 -lt 0 ]; then
-		x="$((($1*-1)/1000))mA"
+		x="$((($1*-1)/1000))"
 	elif [[ $1 -lt 1000 && $1 -gt 0 ]]; then
 		x=$($busybox/awk "BEGIN {printf \"%.2f\n\", $1/10}")
 	elif [[ $1 -lt 10000 && $1 -gt 0 ]]; then
@@ -110,7 +110,7 @@ wait_for(){
 
 logcat(){
 	if [ $LF -eq 1 ]; then
-		echo "$1 $( date +'%d-%m-%Y %H:%M:%S' )" | tee -a $LOG_FILE;
+		echo "$1" \ " $2" \ "$3" \ "$4" \ "$( date +'%d-%m-%Y %H:%M:%S' )" | tee -a $LOG_FILE;
 	fi
 	echo "Battery Charge Control ${ver}: $@" >> /cache/magisk.log
 	log -p i -t "Battery Charge Control ${ver}" "$@"
@@ -128,7 +128,7 @@ if [ -e "$LOG_FILE" ]; then
 fi;
 wait_for 2
 
-logcat "Starting BCC.log"
+logcat "Starting BCC.log" "			    "
 echo "BCC_Magisk $version" | tee -a $LOG_FILE;
 echo "Ok lets start working";
 sleep 2
@@ -205,20 +205,20 @@ while [ $(cat $Status) = "Discharging" ]; do
 		q|Q)
 			if [ `cat $QC` -eq 0 ]; then
 				echo 1 > $QC;
-				logcat "QC=`cat $QC`"
+				logcat "QC=`cat $QC`						 "
 			elif [ `cat $QC` -eq 1 ] && [ `cat $VPH` -eq 0 ]; then
 				echo 1 > $VPH;
-				logcat "VPH=`cat $VPH`"
+				logcat "VPH=`cat $VPH`						 "
 			elif [ `cat $QC` -eq 1 ] && [ `cat $VPH` -eq 1 ]; then
 				echo 0 > $QC; echo 0 > $VPH;
-				logcat "QC=`cat $QC` - VPH=`cat $VPH`"
+				logcat "QC=`cat $QC` - VPH=`cat $VPH`				 "
 			fi
 		;;
 		m|M)
 			vm=$(cat $VM); convert $vm
-			logcat "Manual voltage charge: max ${val}v"
+			logcat "Manual voltage: max ${val}v  	 "
 			clear;
-			echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
+			echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
 			echo ""
 			echo -e "${W}1) 3,92v${N}"
 			echo -e "${W}2) 4,20v${N}"
@@ -248,8 +248,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 					sleep 0.5
 					clear
 					vm=$(cat $VM); convert $vm
-					echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
-					logcat "Manual voltage: new ${val}v"
+					echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
+					logcat "Manual voltage: new ${val}v 	 "
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
@@ -264,10 +264,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo ""
 					echo ""
 					echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-					sleep 5
+					sleep 2
 					echo ""
 					echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-					sleep 5
+					sleep 2
 					MV=1
 					AV=0
 				;;
@@ -287,8 +287,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 					sleep 0.5
 					clear
 					vm=$(cat $VM); convert $vm
-					echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
-					logcat "Manual voltage: new ${val}v"
+					echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
+					logcat "Manual voltage: new ${val}v 	 "
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
@@ -303,10 +303,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo ""
 					echo ""
 					echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-					sleep 5
+					sleep 2
 					echo ""
 					echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-					sleep 5
+					sleep 2
 					MV=1
 					AV=0
 				;;
@@ -326,8 +326,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 					sleep 0.5
 					clear
 					vm=$(cat $VM); convert $vm
-					echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
-					logcat "Manual voltage: new ${val}v"
+					echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
+					logcat "Manual voltage: new ${val}v 	 "
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
@@ -342,10 +342,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo ""
 					echo ""
 					echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-					sleep 5
+					sleep 2
 					echo ""
 					echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-					sleep 5
+					sleep 2
 					MV=1
 					AV=0
 				;;
@@ -366,8 +366,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 					sleep 0.5
 					clear
 					vm=$(cat $VM); convert $vm
-					echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
-					logcat "Manual voltage: new ${val}v"
+					echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
+					logcat "Manual voltage: new ${val}v 	 "
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
@@ -382,10 +382,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo ""
 					echo ""
 					echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-					sleep 5
+					sleep 2
 					echo ""
 					echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-					sleep 5
+					sleep 2
 					MV=1
 					AV=0
 				;;
@@ -418,8 +418,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 					sleep 0.5
 					clear
 					vm=$(cat $VM); convert $vm
-					echo -e "${W}Actual voltage max charge:${N} ${G}${val}v${N}"
-					logcat "Manual voltage: new ${val}v"
+					echo -e "${W}Actual voltage max:${N} ${G}${val}v${N}"
+					logcat "Manual voltage: new ${val}v 	 "
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
@@ -434,10 +434,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo ""
 					echo ""
 					echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-					sleep 5
+					sleep 2
 					echo ""
 					echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-					sleep 5
+					sleep 2
 					MV=1
 					AV=0
 				;;
@@ -467,10 +467,10 @@ while [ $(cat $Status) = "Discharging" ]; do
 			echo ""
 			echo ""
 			echo "BCC is set to recharge the battery by adjusting the most suitable voltage automatically up to $amc%"
-			sleep 5
+			sleep 2
 			echo ""
 			echo "Connect the charger and press 0 followed by enter to begin (it may take a long time)"
-			sleep 5
+			sleep 2
 			AV=1
 			MV=0
 		;;
@@ -489,12 +489,16 @@ while [ $(cat $Status) = "Discharging" ]; do
 			wait_for 3
 		;;
 		*)
-			clear;
-			echo "Invalid option, please try again"
-			sleep 1
-			exit 1
+			read
+			#clear;
+			#echo "Invalid option, please try again"
+			#sleep 1
+			#exit 1
 		;;
 	esac
+	if [ $(cat $Status) = "Charging" ]; then
+		echo "Char." \ "Temp." \ \ \ " Volt" \ \ \ \ \ \ "Cur." \ \ \ \ \ \ "	  Time" | tee -a $LOG_FILE;
+	fi
 	while [ $(cat $Status) = "Charging" ]; do
 		if [[ `cat $BCE` -eq 0 || `cat $CE` -eq 0 ]]; then
 			echo 1 > $BCE; echo 1 > $CE;
@@ -630,56 +634,49 @@ while [ $(cat $Status) = "Discharging" ]; do
 		t=`cat $Temp`
 		if [ "$t" -ne "$t_old" ]; then
 			t_old=$t;
-			if [ "$t" -lt "$tmin" ]; then
-				tmin=$t; convert $tmin
-				logcat "`cat $Capacity`% - Min T: ${val}°"
-				#cn=`cat $CN`; convert $cn
-				#logcat "Actual Current: $val"
-				#vn=`cat $VN`; convert $vn
-				#logcat "Actual Voltage: ${val}v"
+			if [ "$t_old" -lt "$tmin" ]; then
+				tmin=$t_old; convert $tmin
+				logcat "`cat $Capacity`%" " ${val}°-" "			" "		"
+			elif [ "$t_old" -gt "$tmax" ]; then
+				tmax=$t_old; convert $tmax
+				logcat "`cat $Capacity`%" " ${val}°+" "		" "			"
 			fi;
-			if [ "$t" -gt "$tmax" ]; then
-				tmax=$t; convert $tmax
-				logcat "`cat $Capacity`% - Max T: ${val}°"
-				#cn=`cat $CN`; convert $cn
-				#logcat "Actual Current: $val"
-				#vn=`cat $VN`; convert $vn
-				#logcat "Actual Voltage: ${val}v"
-			fi;
-		fi
+		fi;
 		#Voltage control
-		v=`cat $VN`; v=$(($v/10));
+		v=`cat $VN`; v=$(($v / 10000)); #v=$($v | $busybox/cut -f1 -d'.')
 		if [ "$v" -ne "$v_old" ]; then
 			v_old=$v;
-			if [ "$v" -lt "$vmin" ]; then
-				vmin=$(($v*10)); convert $vmin
-				logcat "`cat $Capacity`% - Min V: ${val}v"
+			if [ "$v_old" -lt "$vmin" ]; then
+				vmin=$v_old; x=$($busybox/awk "BEGIN {printf \"%.2f\n\", ${vmin}/100}")
+				#vmin=$(($v_old / 100));
+				logcat "`cat $Capacity`%" "		" "  ${x}v-" "			"
+			elif [ "$v_old" -gt "$vmax" ]; then
+				vmax=$v_old; x=$($busybox/awk "BEGIN {printf \"%.2f\n\", ${vmax}/100}")
+				#vmax=$(($v_old / 100));
+				logcat "`cat $Capacity`%" "		" "  ${x}v+" "			"
 			fi;
-			if [ "$v" -gt "$vmax" ]; then
-				vmax=$(($v*10)); convert $vmax
-				logcat "`cat $Capacity`% - Max V: ${val}v"
-			fi;
-		fi
+		fi;
 		#Current control
-		c=`cat $CN`; c=$(($c/1000));
-		if [ "$c" -ne "$c_old" ]; then
-			c_old=$c;
-			if [ "$c" -lt "$cmin" ]; then
-				cmin=$(($c*1000)); convert $cmin
-				logcat "`cat $Capacity`% - Min C: $val"
+		c=`cat $CN`; convert $c; #c=$($c | $busybox/cut -f1 -d',')
+		if [ "$val" -ne "$c_old" ]; then
+			c_old=$val;
+			if [ "$c_old" -lt "$cmin" ]; then
+				cmin=$c_old
+				#cmin=$(($c_old*1000)); convert $cmin
+				logcat "`cat $Capacity`%" "		" "		" "${val}mA-	"
+			elif [ "$c_old" -gt "$cmax" ]; then
+				cmax=$c_old
+				#cmax=$(($c_old*1000)); convert $cmax
+				logcat "`cat $Capacity`%" "		" "		" "${val}mA+	"
 			fi;
-			if [ "$c" -gt "$cmax" ]; then
-				cmax=$(($c*1000)); convert $cmax
-				logcat "`cat $Capacity`% - Max C: $val"
-			fi;
-		fi
+		fi;
 		if [ $(cat $Capacity) -eq $amc ]; then
 			echo ""
 			echo ""
 			echo -e "${W}Completed!${N}"
 			echo 0 > $BCE; echo 0 > $CE;
 			temp=`cat $Temp`; convert $temp
-			logcat "`cat $Capacity`% - Completed! - Temp: ${val}°"
+			logcat "`cat $Capacity`%" " ${val}°" "Completed!" "		"
 			su -c dumpsys batterystats --reset
 			sleep 5
 		fi
