Added change state detection charging/discarging (to be fixed)

diff --git a/system/bin/bcc_magisk b/system/bin/bcc_magisk
--- a/system/bin/bcc_magisk
+++ b/system/bin/bcc_magisk
@@ -39,11 +39,11 @@ t=`cat $Temp`
 tmin=$t
 t_old=$t
 tmax=$t
-v=`cat $VN`
+v=`cat $VN`; v=$(($v/10000))
 vmin=$v
 v_old=$v
 vmax=$v
-c=`cat $CN`
+c=`cat $CN`; c=$((($c*-1)/1000))
 cmin=$c
 c_old=$c
 cmax=$c
@@ -73,9 +73,9 @@ W='\e[01;37m'
 
 #Functions
 convert(){
-	#Convert to decimal value
+	#Convert value
 	if [ $1 -lt 0 ]; then
-		x="$((($1*-1)/1000))"
+		x=$((($1*-1)/1000))
 	elif [[ $1 -lt 1000 && $1 -gt 0 ]]; then
 		x=$($busybox/awk "BEGIN {printf \"%.2f\n\", $1/10}")
 	elif [[ $1 -lt 10000 && $1 -gt 0 ]]; then
@@ -194,14 +194,14 @@ while [ $(cat $Status) = "Discharging" ]; do
 		fi
 	fi
 	echo "e) Exit"
-	echo""
-	echo""
+	echo ""
+	echo ""
 	echo -e "${W}0) ------ to start charging ------${N}"
-	echo""
-	echo""
+	echo ""
+	echo ""
 	echo -n "\n[CHOICE]: "
-	read -r c
-	case $c in
+	read -r -s -n1 -t 1 character
+	case $character in
 		q|Q)
 			if [ `cat $QC` -eq 0 ]; then
 				echo 1 > $QC;
@@ -230,8 +230,8 @@ while [ $(cat $Status) = "Discharging" ]; do
 			echo -e "${W}5) Custom voltage${N}"
 			echo "b) Back"
 			echo -n "\n[CHOICE]: "
-			read -r c
-			case $c in
+			read -r character
+			case $character in
 				1)
 					if [ -f $System_temp_level ] && [ $(cat $System_temp_level) -eq 0 ]; then
 						echo 1 > $System_temp_level
@@ -253,9 +253,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [[ $c -gt 0 && $c -lt 101 ]]; then
-						amc=$c
+					read -r character
+					if [[ $character -gt 0 && $character -lt 101 ]]; then
+						amc=$character
 					else
 						echo "Invalid option, please try again"
 						sleep 3
@@ -292,9 +292,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [[ $c -gt 0 && $c -lt 101 ]]; then
-						amc=$c
+					read -r character
+					if [[ $character -gt 0 && $character -lt 101 ]]; then
+						amc=$character
 					else
 						echo "Invalid option, please try again"
 						sleep 3
@@ -331,9 +331,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [[ $c -gt 0 && $c -lt 101 ]]; then
-						amc=$c
+					read -r character
+					if [[ $character -gt 0 && $character -lt 101 ]]; then
+						amc=$character
 					else
 						echo "Invalid option, please try again"
 						sleep 3
@@ -371,9 +371,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [ $c -gt 0 ] && [ $c -lt 101 ]; then
-						amc=$c
+					read -r character
+					if [ $character -gt 0 ] && [ $character -lt 101 ]; then
+						amc=$character
 					else
 						echo "Invalid option, please try again"
 						sleep 3
@@ -394,9 +394,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					echo -e "${W}Insert the charge voltage in mV without adding the unit of measurement (example 4,18V = 4180mV)${N}"
 					echo -e "${W}Accepted values: min=3920 max=4400${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [[ $c -gt 3920 && $c -lt 4400 ]]; then
-						custom_v=$c
+					read -r character
+					if [[ $character -gt 3920 && $character -lt 4400 ]]; then
+						custom_v=$character
 					else
 						read
 						#echo "Invalid option, please try again"
@@ -423,9 +423,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 					clear;
 					echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 					echo -n "\n[CHOICE]: "
-					read -r c
-					if [ $c -gt 0 ] && [ $c -lt 101 ]; then
-						amc=$c
+					read -r character
+					if [ $character -gt 0 ] && [ $character -lt 101 ]; then
+						amc=$character
 					else
 						echo "Invalid option, please try again"
 						sleep 3
@@ -456,9 +456,9 @@ while [ $(cat $Status) = "Discharging" ]; do
 			clear;
 			echo -e "${W}How much percentage do you want to recharge? (enter only the percentage value without '%')${N}"
 			echo -n "\n[CHOICE]: "
-			read -r c
-			if [ $c -gt 0 ] && [ $c -lt 101 ]; then
-				amc=$c
+			read -r character
+			if [ $character -gt 0 ] && [ $character -lt 101 ]; then
+				amc=$character
 			else
 				echo "Invalid option, please try again"
 				sleep 3
@@ -488,14 +488,20 @@ while [ $(cat $Status) = "Discharging" ]; do
 			clear;
 			wait_for 3
 		;;
-		*)
-			read
-			#clear;
-			#echo "Invalid option, please try again"
-			#sleep 1
-			#exit 1
-		;;
+		#*)
+		#	if [ -z "$character" ]; then
+		#		continue
+		#	else
+		#		clear;
+		#		echo "Invalid option, please try again"
+		#		sleep 1
+		#		exit 1
+		#	fi
+		#;;
 	esac
+	#if [ -n $character ]; then
+	#	character=""
+	#fi
 	if [ $(cat $Status) = "Charging" ]; then
 		echo "Char." \ "Temp." \ \ \ " Volt" \ \ \ \ \ \ "Cur." \ \ \ \ \ \ "	  Time" | tee -a $LOG_FILE;
 	fi
@@ -649,34 +655,41 @@ while [ $(cat $Status) = "Discharging" ]; do
 			if [ "$v_old" -lt "$vmin" ]; then
 				vmin=$v_old; x=$($busybox/awk "BEGIN {printf \"%.2f\n\", ${vmin}/100}")
 				#vmin=$(($v_old / 100));
-				logcat "`cat $Capacity`%" "		" "  ${x}v-" "			"
+				logcat "`cat $Capacity`%" "		" "  ${x}v- " "			"
 			elif [ "$v_old" -gt "$vmax" ]; then
 				vmax=$v_old; x=$($busybox/awk "BEGIN {printf \"%.2f\n\", ${vmax}/100}")
 				#vmax=$(($v_old / 100));
-				logcat "`cat $Capacity`%" "		" "  ${x}v+" "			"
+				logcat "`cat $Capacity`%" "		" "  ${x}v+ " "			"
 			fi;
 		fi;
 		#Current control
-		c=`cat $CN`; convert $c; #c=$($c | $busybox/cut -f1 -d',')
-		if [ "$val" -ne "$c_old" ]; then
-			c_old=$val;
-			if [ "$c_old" -lt "$cmin" ]; then
-				cmin=$c_old
-				#cmin=$(($c_old*1000)); convert $cmin
-				logcat "`cat $Capacity`%" "		" "		" "${val}mA-	"
-			elif [ "$c_old" -gt "$cmax" ]; then
-				cmax=$c_old
-				#cmax=$(($c_old*1000)); convert $cmax
-				logcat "`cat $Capacity`%" "		" "		" "${val}mA+	"
+		c=`cat $CN`;
+		if [ $c -lt -1000 ]; then
+			convert $c; #c=$($c | $busybox/cut -f1 -d',')
+			if [ "$val" -ne "$c_old" ]; then
+				c_old=$val;
+				if [ "$c_old" -lt "$cmin" ]; then
+					cmin=$c_old
+					#cmin=$(($c_old*1000)); convert $cmin
+					if [ $cmin -lt 100 ]; then
+						logcat "`cat $Capacity`%" "		" "		" "${cmin}mA-		"
+					else
+						logcat "`cat $Capacity`%" "		" "		" "${cmin}mA-  	"
+					fi
+				elif [ "$c_old" -gt "$cmax" ]; then
+					cmax=$c_old
+					#cmax=$(($c_old*1000)); convert $cmax
+					logcat "`cat $Capacity`%" "		" "		" "${cmax}mA+ 	"
+				fi;
 			fi;
-		fi;
+		fi
 		if [ $(cat $Capacity) -eq $amc ]; then
 			echo ""
 			echo ""
 			echo -e "${W}Completed!${N}"
 			echo 0 > $BCE; echo 0 > $CE;
 			temp=`cat $Temp`; convert $temp
-			logcat "`cat $Capacity`%" " ${val}°" "Completed!" "		"
+			logcat "`cat $Capacity`%" " ${val}°" "	Completed!" "		"
 			su -c dumpsys batterystats --reset
 			sleep 5
 		fi
